### ISSUE TITLE
Reset user traffic every n days

### ISSUE THREAD

**Issue by freenet4ever** [enfein/mieru#105]
Can we add this feature:
Record the time when user connected for the first time. if n days passed reset traffic of user.

                {
                    "days": 30,
                    "megabytes": 10240
                    "reset":1
                }
after 30 days reset traffic stats of user

**Comment by enfein** [comment]
If you are talking about resetting the statistics, rather than using the statistics to limit user's usage, then I believe there is no good reason to support this feature.

The type of this statistics is designed to be counter, which can only increase.

Issue #103 will give you the raw statistics data, which you can query and calculate the user's usage at a given time window.
