### ISSUE TITLE
add user CLI command

### ISSUE THREAD

**Issue by cr4zyfish** [enfein/mieru#122]
I see there is `mita delete user` command. which hot reloads config i guess.
adding a command like this might be helpful: 

`mita add user username password`
or
`mita add user username password days megabytes days megabytes ...`

Also is it possible to get metrics per user?

**Comment by enfein** [comment]
The `mita delete user` CLI doesn't do reload. You need to execute `mita reload` to refresh the configuration.

The reason why there is a `mita delete user` and `mieru delete profile` command is due to the special handling of the user and profile in the server and client configuration. When you do `mita apply config` or `mieru apply config`, you don't need to provide the full configuration, instead, the configuration you provided is patched to existing configuration. For user and profile, the patching will add new users and new profiles if they don't exist before. Thus, we provide command to delete users and profiles that you don't want.

To add a new user, it is very simple to apply the configuration like this:

```json
{
    "users": [
        {
            "name": "ducaiguozei",
            "password": "xijinping",
            "quotas": [
                {
                    "days": 1,
                    "megabytes": 1024
                },
                {
                    "days": 30,
                    "megabytes": 10240
                }
            ]
        }
    ]
}
```

Thus, I don't think there is a need to add another command for that.

Metrics per user is already available. You can find it from `mita get metrics` command.
