### ISSUE TITLE
Feature request: proxy authentication and etc

### ISSUE THREAD

**Issue by Gitscarlet** [enfein/mieru#147]
Hello I have these feature requests. Please implement any of them you think its more helpful.

1.  in mieru client config we have this:
`   "socks5ListenLAN": false,`
But users can access socks proxy without authentication. So can we have user and password when socks5ListenLAN is true?

2. in mita we have this:
```
    "egress": {
        "proxies": [
            {
                "name": "cloudflare",
                "protocol": "SOCKS5_PROXY_PROTOCOL",
                "host": "127.0.0.1",
                "port": 4000
            }
        ],
        "rules": [
            {
                "ipRanges": ["*"],
                "domainNames": ["*"],
                "action": "PROXY",
                "proxyName": "cloudflare"
            }



```

But we can not use a remote socks proxy that requires authentication. Authentication here is no for adding encryption, we just dont want other people to connect to our socks proxy server.

3. add http proxy to lan and outbound proxy with authentication. (currently it only supports socks5)

4. add a command to apply the whole config instead of patching the existing config.

4. set expiry date for accounts.

thanks

**Comment by enfein** [comment]
1. No problem.
2. No problem. However, for security, you should only connect to localhost socks5 proxy in VPS. In that case, the authentication is useless.
3. HTTP proxy LAN is already supported. HTTP outbound proxy can't be supported because we can't convert socks5 into HTTP without deep packet inspection.
4. If you use the same command to apply the whole configuration, it should work. If not, file a bug.
5. Probably not necessary. This can be easily done with a management script. No need to build in this feature inside mieru.
