### ISSUE TITLE
mieru client is not running: ClientLifecycleService.GetStatus() failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp [::1]:8964: con nectex: No connection could be made because the target machine actively refused it."

### ISSUE THREAD

**Issue by Lswx2017** [enfein/mieru#23]
What is the role of rpcPort and socks5Port?
The above error is reported when mieru start is executed.

**Comment by enfein** [comment]
Most probably you have this error because your computer is slow, or your anti-virus program makes mieru slow, or you don't allow firewall in time, etc.

I have uploaded a patch to increase the timeout. Based on the error message I believe you use Windows. Please try this build and see if this issue is resolved.

[mieru_1.6.0_windows_amd64.zip](https://github.com/enfein/mieru/files/9172595/mieru_1.6.0_windows_amd64.zip)

**Comment by enfein** [comment]
`socks5Port` is where the traffic is getting proxyed, while `rpcPort` controls the behavior of mieru program. You need to tell `socks5Port` to other programs like Chrome. `rpcPort` is used only by mieru itself as an implementation detail.

**Comment by Aquarii** [comment]
Hi
I get the same error on Windows 10. it started yesterday out of nowhere. 
this is the log:
```
2024-06-05T09:28:15+03:30 INFO mieru client RPC server is running
2024-06-05T09:28:15+03:30 INFO Initializing client multiplexer
2024-06-05T09:28:15+03:30 INFO Mux multiplexing factor is set to 3
2024-06-05T09:28:15+03:30 INFO mieru client HTTP proxy server is running
2024-06-05T09:28:15+03:30 FATAL listen on socks5 address tcp "127.0.0.1:1080" failed: listen tcp 127.0.0.1:1080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```
what does the fatal log mean? 

btw, port 8964 is not used and is open. I even turned off my firewall completely to see if it was the problem, but it wasn't.

**Comment by Aquarii** [comment]
btw, it takes a very very long time to throw the error. is there any option to lower its timeout?
