### ISSUE TITLE
mieru v2 and beyond

### ISSUE THREAD

**Issue by enfein** [enfein/mieru#54]
Recently there have been reports (issue #50, issue #53, Revolt Chat) of network block with both TCP and UDP protocols in China. It means the current mieru protocols are insufficient to provide a stable proxy services. Even though the original design of mieru has taken a plenty of lessons from shadowsocks and v2ray (vmess), new techniques have been deployed by GFW to identify proxy services. A few known weaknesses of the current protocols are listed below:

1. A full encryption protocol has higher entropy than normal packets. This has been discussed on https://github.com/net4people/bbs/issues/136.
2. The RTT among the first a few packets have special timing characteristic. This is due to the fact that socks5 handshake is faster than dial and connect to the destination server.
3. Some popular websites has deterministic number of connections and timestamps. This information needs to be hidden by multiplexing.

My current plan is to resolve 1 quickly in mieru v2 protocol. v2 means that it breaks backward compatibilities and you must use the same major version of the server and the client. To address 2 and 3, I have an ambitious plan that will take a long time to develop, so it will probably become mieru v3 at a certain point of time in the future.

Thank you for the support.

**Comment by mrmmg** [comment]
Go on, 💪

**Comment by alidxdydz** [comment]
Hi,

I believe this is the second time that I see someone is refering to Entropy of encrypted content.
I first saw this claim in Dust documentation and one of its issues:
[Dust v1 - GitHub](https://github.com/blanu/Dust/tree/master/historical/v1)
[Dust v2 - GitHub](https://github.com/blanu/Dust/blob/master/historical/haskell2014/Dust/README)
[Dust - Issue](https://github.com/blanu/Dust/issues/23)
[Dust - YouTube](https://youtu.be/u0iueUlY6dQ)

Then I got more interested about DPI and saw these on the Internet:

[SymTCP - GitHub](https://github.com/seclab-ucr/SymTCP)
[SymTCP - YouTube](https://youtu.be/Fp9fLRPY7hI)

[Geneva - GitHub](https://github.com/kkevsterrr/geneva)
[Geneva - Papers](https://geneva.cs.umd.edu/papers/)
[Geneva - YouTube1](https://youtu.be/NM-h3WoAYEc)
[Geneva - YouTube2](https://youtu.be/b9F696-oax0)

I just wanted to mention these projects here so that some people take a look at them (specially the presentation videos on YouTube take less time).

Dust is already listed in [Pluggable Transports Repo](https://github.com/obfuscation/documentation) but there isn't clear explanation about implementing and using it.
Therefore, I wonder if these projects are only going to be Thesis-based university specific projects or are we really going to use them in practice and real life.

I thank you for your great work and I hope the upcomming versions of mieru will be more helpful.

**Comment by alidxdydz** [comment]
Hi,

I believe this is the second time that I see someone is refering to Entropy of encrypted content.
I first saw this claim in Dust documentation and one of its issues:

[Dust v1 - GitHub](https://github.com/blanu/Dust/tree/master/historical/v1)
[Dust v2 - GitHub](https://github.com/blanu/Dust/blob/master/historical/haskell2014/Dust/README)
[Dust - Issue](https://github.com/blanu/Dust/issues/23)
[Dust - YouTube](https://youtu.be/u0iueUlY6dQ)

Then I got more interested about DPI and saw these on the Internet:

[SymTCP - GitHub](https://github.com/seclab-ucr/SymTCP)
[SymTCP - YouTube](https://youtu.be/Fp9fLRPY7hI)

[Geneva - GitHub](https://github.com/kkevsterrr/geneva)
[Geneva - Papers](https://geneva.cs.umd.edu/papers/)
[Geneva - YouTube1](https://youtu.be/NM-h3WoAYEc)
[Geneva - YouTube2](https://youtu.be/b9F696-oax0)

I just wanted to mention these projects here so that some people take a look at them (specially the presentation videos on YouTube take less time).

Dust is already listed in [Pluggable Transports Repo](https://github.com/obfuscation/documentation) but there isn't clear explanation about implementing and using it.
Therefore, I wonder if these projects are only going to be Thesis-based university specific projects or are we really going to use them in practice and real life.

@enfein , I thank you for your great work and I hope the upcomming versions of mieru will be more helpful.
