### ISSUE TITLE
Add ChaCha20-Poly1305 for Low-End Devices

### ISSUE THREAD

**Issue by APT-ZERO** [enfein/mieru#98]
Hey, Could you please add another encryption like ChaCha20-Poly1305 for low-end devices?

**Comment by enfein** [comment]
The hardware acceleration of AES is supported by Intel and AMD x86 CPUs since 2011. For ARM, it is introduced since ARMv8-A (Cortex A53 and Cortex A57). The earliest supported mobile devices and chips are iPhone5S and Qualcomm Snapdragon 805. It is fair to say more than 99% of mobile phones have AES acceleration.

The biggest benefit of ChaCha20-Poly1305 would be ARMv7 OpenWRT devices.

Given that said, I think this feature is a low priority.
